<?php declare(strict_types=1);

// Regression: inlining a match-wrapper that returns DictMethod(evidenceParam->m)
// must substitute the evidence Local with the call-site FnRef. Previously
// substituteExpr fell through `default => $expr` for DictMethod, leaving
// unbound `__ev_*` locals (Char8.maximum ← listMaximum).
return json_decode(<<<'JSON'
{"tag":"module","functions":[{"tag":"function","name":"listMax","params":["__ev_Ord_1","xs"],"type":{"tag":"type_arrow","from":{"tag":"type_app","con":{"tag":"type_con","name":"List"},"args":[{"tag":"type_con","name":"Char"}]},"to":{"tag":"type_con","name":"Char"}},"body":{"tag":"block","items":[{"tag":"match_return","scrutinee":{"tag":"local","name":"xs"},"exhaustive":true,"arms":[{"tag":"arm","pattern":{"tag":"pat_nil"},"body":{"tag":"block","items":[{"tag":"ret","value":{"tag":"const","value":0}}]},"guards":[]},{"tag":"arm","pattern":{"tag":"pat_cons","head":{"tag":"pat_var","name":"x"},"tail":{"tag":"pat_var","name":"rest"}},"body":{"tag":"block","items":[{"tag":"ret","value":{"tag":"expr_call","callee":"apply2","args":[{"tag":"dict_method","evidence":{"tag":"local","name":"__ev_Ord_1"},"method":"max"},{"tag":"local","name":"x"},{"tag":"local","name":"rest"}]}}]},"guards":[]}]}]},"export":false,"instanceMethod":false,"entryPoint":false},{"tag":"function","name":"maximum","params":["xs"],"type":{"tag":"type_arrow","from":{"tag":"type_app","con":{"tag":"type_con","name":"List"},"args":[{"tag":"type_con","name":"Char"}]},"to":{"tag":"type_con","name":"Char"}},"body":{"tag":"block","items":[{"tag":"call","callee":"listMax","args":[{"tag":"fn","name":"__ev_Ord_Char"},{"tag":"local","name":"xs"}],"dest":0},{"tag":"ret","value":{"tag":"temp","id":0}}]},"export":false,"instanceMethod":false,"entryPoint":false},{"tag":"function","name":"apply2","params":["f","a","b"],"type":{"tag":"type_arrow","from":{"tag":"type_con","name":"Char"},"to":{"tag":"type_con","name":"Char"}},"body":{"tag":"block","items":[{"tag":"call_value","callee":{"tag":"local","name":"f"},"args":[{"tag":"local","name":"a"},{"tag":"local","name":"b"}],"dest":1},{"tag":"ret","value":{"tag":"temp","id":1}}]},"export":false,"instanceMethod":false,"entryPoint":false}],"data":[],"instanceEvidence":[],"entryMain":null}
JSON, true, flags: JSON_THROW_ON_ERROR);
